/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: C:\Users\yeisme\code\language_dev\ffi_dev\learn_project\swig_cpp_go\src\calculator.i

package calculator

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_calculator_887571f7e99a2043(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_calculator_887571f7e99a2043(swig_intgo arg1);
extern uintptr_t _wrap_new_Calculator_calculator_887571f7e99a2043(void);
extern void _wrap_delete_Calculator_calculator_887571f7e99a2043(uintptr_t arg1);
extern double _wrap_Calculator_add_calculator_887571f7e99a2043(uintptr_t arg1, double arg2, double arg3);
extern double _wrap_Calculator_subtract_calculator_887571f7e99a2043(uintptr_t arg1, double arg2, double arg3);
extern double _wrap_Calculator_multiply_calculator_887571f7e99a2043(uintptr_t arg1, double arg2, double arg3);
extern double _wrap_Calculator_divide_calculator_887571f7e99a2043(uintptr_t arg1, double arg2, double arg3);
extern swig_intgo _wrap_Calculator_getOperationCount_calculator_887571f7e99a2043(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_calculator_887571f7e99a2043(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_calculator_887571f7e99a2043(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrCalculator uintptr

func (p SwigcptrCalculator) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCalculator) SwigIsCalculator() {
}

func NewCalculator() (_swig_ret Calculator) {
	var swig_r Calculator
	swig_r = (Calculator)(SwigcptrCalculator(C._wrap_new_Calculator_calculator_887571f7e99a2043()))
	return swig_r
}

func DeleteCalculator(arg1 Calculator) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Calculator_calculator_887571f7e99a2043(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrCalculator) Add(arg2 float64, arg3 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_Calculator_add_calculator_887571f7e99a2043(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrCalculator) Subtract(arg2 float64, arg3 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_Calculator_subtract_calculator_887571f7e99a2043(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrCalculator) Multiply(arg2 float64, arg3 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_Calculator_multiply_calculator_887571f7e99a2043(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrCalculator) Divide(arg2 float64, arg3 float64) (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_Calculator_divide_calculator_887571f7e99a2043(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrCalculator) GetOperationCount() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Calculator_getOperationCount_calculator_887571f7e99a2043(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type Calculator interface {
	Swigcptr() uintptr
	SwigIsCalculator()
	Add(arg2 float64, arg3 float64) (_swig_ret float64)
	Subtract(arg2 float64, arg3 float64) (_swig_ret float64)
	Multiply(arg2 float64, arg3 float64) (_swig_ret float64)
	Divide(arg2 float64, arg3 float64) (_swig_ret float64)
	GetOperationCount() (_swig_ret int)
}


